"""create user and movie tables

Revision ID: 5426f498f77d
Revises: 05e6fdec17d1
Create Date: 2025-05-22 15:46:21.982385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5426f498f77d'
down_revision: Union[str, None] = '05e6fdec17d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'poster_url',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               nullable=False)
    op.alter_column('movies', 'owner_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('movies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.alter_column('movies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_constraint('movies_owner_id_fkey', 'movies', type_='foreignkey')
    op.create_foreign_key(None, 'movies', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('users', 'is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.drop_constraint(None, 'movies', type_='foreignkey')
    op.create_foreign_key('movies_owner_id_fkey', 'movies', 'users', ['owner_id'], ['id'])
    op.alter_column('movies', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('movies', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True)
    op.alter_column('movies', 'owner_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('movies', 'poster_url',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
